### ISSUE TITLE
Run an application against a Kubernetes deployment

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2938]
Our manual deployement docs include [running a sample workload against the cluster](https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-aws.html#step-9-run-a-sample-workload). This is more complicated when running CockroachDB in Kubernetes, and we have gotten a lot of questions for the community on this. 

We need to expand our Kubernetes tutorials to show how to:
- [ ] Run a sample workload from within the same Kubernetes cluster as CockroachDB (secure) (helpful details may be in #2458)
- [ ] Run a sample workload from within the same Kubernetes cluster as CockroachDB (insecure) (helpful details may be in #860)
- [ ] Run a sample workload from a separate Kubernetes cluster (secure)
- [ ] Run a sample workload from a separate Kubernetes cluster (insecure) (helpful details may be in #1535)

Also see https://github.com/cockroachdb/docs/issues/4219.

**Comment by jseldess** [comment]
From chat btw @sploiselle and @a-robinson:

> using our default kubernetes yaml file, how do you connect an application or a load gen to your cluster? I’m not looking to get into the actual machines, but am looking for the connection string

> `postgres://root@cockroachdb-public:26257/photos?sslmode=disable` for insecure
>
> see https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/example-app-secure.yaml for a secure example

**Comment by holtrdan** [comment]
This is becoming more important in the field. Can we add to our current multi region k8s docs on how application connect to K8s (Ingress) and getting data out (egress).

**Comment by jseldess** [comment]
@holtrdan, is it most important to cover cases where an application is outside of the kubernetes cluster, or getting data to a system outside of the kubernetes cluster, or is doing all of this from within a single kubernetes cluster also important?

**Comment by holtrdan** [comment]
Depends - Single region K8s you're most likely running your app in the same k8s cluster as the db. If your running multi-region k8s I would say the priority is on apps outside k8s

**Comment by jseldess** [comment]
Recent related questions on forum and SO:
- https://forum.cockroachlabs.com/t/expose-cockroach-multi-region-database-to-public/3279/2
- https://stackoverflow.com/questions/58722737/how-to-connect-to-cockroachdb-container-from-other-container-using-docker-compos

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
