### ISSUE TITLE
Under- or un-documented features

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2944]
For 2.1, we need to expand our docs on:

- [x] Window functions (#710)
- [x] Online schema changes (#3492)
   - Only have this [blog post](https://www.cockroachlabs.com/blog/how-online-schema-changes-are-possible-in-cockroachdb/)
   - Priority 1: Also mention how we're working on improvements.

**Comment by jseldess** [comment]
@bdarnell, @petermattis, what is our current opinion about documenting `crdb_internal`?

**Comment by jseldess** [comment]
Comment from @bdarnell on `crdb_internal`:

> In general my thinking is that crdb_internal should remain internal-only and undocumented. we should take the stuff that's useful enough to document and put it behind SHOW commands or maybe make a separate `crdb_catalog` virtual schema with more stability/documentation guarantees

**Comment by jseldess** [comment]
These features tracked separately, as potential docs projects for 2.2.:

- [ ] Joins (#534) 
- [ ] Placeholder support (#2168) 
- [ ] Server-side Prepared Statements (#1333)
- [ ] Interleaved secondary indexes (#761)

**Comment by jseldess** [comment]
Window functions and online schema changes are live, so closing this.
