### ISSUE TITLE
 Write the Docs open source writing day

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2946]
Plan and execute CockroachDB's involvement in the [open-source writing day at the Write the Docs conference](http://www.writethedocs.org/conf/portland/2018/writing-day/).

Action items:
- [x] 1. Ask WTD to list Cockroach Labs as an official writing day project. 
- [x] 2. Identify the work we want contributors to take on.
- [x] 3. Come up with a clear GitHub issue and labeling scheme.
- [x] 4. Open PR to add Cockroach to the writer day page with details about help we're looking for.
- [x] 5. Create/curate guidance for writing day contributors.
- [x] 6. Post-conference: Analyze outcomes/learnings and share results and insights as a 5-min presentation at a Tuesday company meeting.

**Comment by jseldess** [comment]
@Amruta-Ranade, I'll handle the first box. The rest is yours, with help from me and the team, of course ;).

**Comment by jseldess** [comment]
Someone at WTD agreed to list CRDB on the writing day page. We need to open a PR adding us to the [listed projects](http://www.writethedocs.org/conf/portland/2018/writing-day/#projects). Before we can do that, though, we need to tackle action items 2 and 3, @Amruta-Ranade.

**Comment by Amruta-Ranade** [comment]
**Action Plan**

**Jesse:**
- Identify undocumented/under-documented features
- Identify a few product issues/features to document (similar to the `ADD COLUMN` feature given as take-home test for interviewees)

**Amruta:**
_Complete by Friday (04/26)_
- Create GitHub issues for:
    - Copy-to-clipboard functions
    - Test the Docs setup process and provide feedback
    - Improve our use of tables in Markdown
    - Test and provide feedback on Getting Started docs
    - Test and provide feedback on Production docs
    - Provide feedback about whether the docs are understandable/scannable 
        - Identify docs we want them to provide feedback on

_Complete by Monday (04/30)_
- Update the Write The Docs Writing Day page.

**Comment by Amruta-Ranade** [comment]
Presented at the team meeting..all boxes checked. Closing the issue :)
