### ISSUE TITLE
Follow-up improvements to multi-region Kubernetes guide

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#3591]
Unresolved comments from https://github.com/cockroachdb/docs/pull/3558:

- [x]  Port from v2.1 back to v2.0 (for @jseldess)
- [x] Clarify the namespace situation (for @a-robinson)
- [x] Document the firewall requirements (@a-robinson)
- [x] Simulate dc failure instead of node failure - see comment below (for @a-robinson)

**Comment by a-robinson** [comment]
3. Document the firewall requirements (@a-robinson)

**Comment by jseldess** [comment]
Also:

In the multi-region k8s tutorial, instead of simulating node failure I think it would be much more interesting to simulate entire datacenter failure by either scaling the number of VM instances in one of the GKE clusters down to 0 (`gcloud container clusters resize <cluster-name> --zone=<zone> --size=0`) or all the pods in one of the clusters down to 0 (`kubectl scale statefulset cockroachdb --replicas=0 --namespace=<cluster-namespace> --context=<cluster-context>`).

**Comment by jseldess** [comment]
Hey @a-robinson, do you think you'll have time to handle the two bullets assigned to you? If not, not a problem to push to 2.2.

**Comment by a-robinson** [comment]
I'm having trouble reproducing the firewall issue or even understanding how you ran into it in the first place. All of our GCE projects have a "default-allow-internal" firewall rule that allows traffic between all VMs in the network on all ports. Also, all GKE VMs (at least the ones in my personal project) are given a  "gke-<cluster-name>-<cluster-hash>-vms" firewall rule which allows traffic on all ports from VMs inside the project's network to all the VMs in the GKE cluster. And another firewall rule is added for each GKE cluster that allows communication from the pod IP ranges (if/when it falls outside the normal network CIDR) to all VMs in the project.

So I'm really not sure why you ran into a connectivity problem, or why adding a firewall rule that allows traffic to all VMs from all IPs on port 26257 did anything that the existing rules didn't. I'll see if I can repro it in that project, though, since trying in mine hasn't worked.

**Comment by a-robinson** [comment]
Well I'm still not sure why it works in my project without the firewall rule to allow all traffic to port 26257, but I now see why it doesn't work in the shared project that you used (when I remove that rule).

The "default-allow-internal" rule doesn't apply to traffic from pods, because their IP addresses are outside the network CIDR. The `gke-<cluster-name>-<cluster-hash>-vms` rule doesn't apply because pod IP addresses are outside the network CIDR that's used as the acceptable source IP range (10.128.0.0/9). The `gke-<cluster-name>-<cluster-hash>-all` rule doesn't apply because it only allows the pod IPs to target other nodes in the same cluster.
