### ISSUE TITLE
Update and expand the production checklist

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3936]
- [ ] Update our [basic hardware recommendations](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#basic-hardware-recommendations).
    - Instead of a blanket minimum 2GB RAM recommendations, can we provide min RAM guidelines that consider data size and other factors? Probably want general guidelines for either amount of memory per core or amount of memory per data stored. (From https://github.com/cockroachdb/docs/issues/3795) 
    - Add guidance on disk type, disk size, and node/disk ratio (See https://github.com/cockroachdb/docs/issues/4112) 
    - Add guidance on IOPs for disks. Can we provide some guidance or a formula to help users understand how to properly provision their disks? (From https://github.com/cockroachdb/docs/issues/3841)
    - Add recommendations around operating systems. (includes https://github.com/cockroachdb/docs/issues/4035)
    - Add recommendations around file systems. (See https://github.com/cockroachdb/docs/issues/46)
    - Add guidance around `nobarrier`. (See https://github.com/cockroachdb/docs/issues/3962)
    - Add guidance around RAID. (See https://github.com/cockroachdb/docs/issues/3276)
- [ ] Update our [cloud-specific hardware recommendations](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#cloud-specific-recommendations)
    - Per cloud, are the instance type recommendations still right? Can we provide better minimum and recommended specs? What are the updated specs for Cockroach Labs internal testing? 
    - For AWS specifically, we should update our hardware recommendations for EC2.  From https://github.com/cockroachdb/docs/issues/3852: `m5` and `m5d` instances use a new hypervisor that resolves the performance problem in https://heapanalytics.com/blog/engineering/clocksource-aws-ec2-vdso. Our old recommendation of `m3.large` is closest to `m5d.large`. However, I don't think we've tested that configuration. Our current main in-house use of EC2 is now on `m5.xlarge` instances with separate attached EBS volumes.
    - Check with Andy W re: performance between AWS and GCE, and if we want to make any recommendations.
- [x] Update [clock sync recommendations](https://www.cockroachlabs.com/docs/dev/recommended-production-settings.html#basic-hardware-recommendations). (From https://github.com/cockroachdb/docs/issues/3856)
    - We should make it clear that you only want one time sync program running on VMs where cockroach is running.
    -  We should still recommend using google or amazon clock service but with whatever time sync program they are already using. So if they're already using ntp, configure ntp to point to the google or amazon time server. Likewise for chrony.
    - As an advanced option, users who'd rather not use google or amazon can use chrony and enable client side leap smearing (unless they're using a clock source that does server-side smearing). There will not be a leap second before June 2019 at the earliest, so this is not high priority yet.
    - For the choice between google and amazon's time servers: Amazon's time server is only available within EC2, so hybrid environments should use google's instead. For reference, redhat has some docs on options for handling leap seconds: https://access.redhat.com/articles/15145
