### ISSUE TITLE
Change Data Capture (CDC) Iteration 2 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3992]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recwMGmwyrxu9Nt7k
PM: @rolandcrosby 
Eng: @danhhz

**Comment by rolandcrosby** [comment]
- [ ] Need to explain the meanings and origins of the `updated` timestamps. When a cursor is provided, the `updated` timestamps should always match the MVCC timestamps of the emitted rows. However, when a cursor is not provided, the changefeed will perform an initial scan as of the time the changefeed is created, and the `updated` timestamp for each change record emitted in that initial scan will be the timestamp of the initial scan.
  * There's some additional complexity we need to understand and explain here, related to updated timestamps and schema changes. Dan explains it as follows: "a similar thing happens when we have to do a backfill for a schema change. When we do the backfill, the updated timestamp is set to the first timestamp for which the new schema is valid (or something like that, this was matt stuff so it's not as strong in my mental model)"
- [ ] More generally, need to explain CDC's behavior with cursors and MVCC history, and probably explicitly state that we can only emit detailed history within the GC window (i.e. you can't start a changefeed with a cursor pointing a month back and expect to get a version-by-version accounting of everything that happened in your database)

**Comment by danhhz** [comment]
>  you can't start a changefeed with a cursor pointing a month back and expect to get a version-by-version accounting of everything that happened in your database

FYI, if you try this (going back before the gc threshold of either the data or the table metadata) the changefeed will error. Agree it's important to spell out in the docs, just mentioning that we're don't violate any correctness guarantees if someone doesn't read them.

**Comment by rolandcrosby** [comment]
- [ ] Need to list supported and unsupported SQL types and values for Avro changefeeds. Gotchas include:
- Decimals must have precision specified
- Decimals with NaN or infinite values cannot be written as Avro
   - if users are worried that they might destroy their changefeeds with these values, perhaps suggest   adding a check constraint to prevent these values from being inserted into decimal columns that will go to an Avro CDC sink?
- [`time`, `date`, `interval`](https://github.com/cockroachdb/cockroach/issues/32472), [`uuid`, `inet`](https://github.com/cockroachdb/cockroach/issues/34417), [`array`](https://github.com/cockroachdb/cockroach/issues/34420), and [`jsonb`](https://github.com/cockroachdb/cockroach/issues/34421) aren't yet supported (but that may change depending on our investigation of the linked issues; need to make sure we capture the state of what'll be in 2.2)
- [ ] Need to include a table showing the mappings of CockroachDB types to Avro types (like [this table](https://debezium.io/docs/connectors/postgresql/#data-types) in the Debezium docs)

**Comment by rolandcrosby** [comment]
- [ ] Update examples with new default envelope format
- [ ] Document how core changefeeds work and syntax change (`EXPERIMENTAL CHANGEFEED FOR...`)
- [ ] Document the meanings of the metrics in the graphs in the admin UI - [added in this PR](https://github.com/cockroachdb/cockroach/pull/34427)

**Comment by danhhz** [comment]
- [ ] Page describing the tradeoffs between the three settings mentioned in https://github.com/cockroachdb/cockroach/issues/34476

**Comment by rolandcrosby** [comment]
As discussed, highest priority for the 2/11/19 alpha docs is the `kv.rangefeed.enabled` cluster setting, followed by core changefeed and envelope format documentation.

**Comment by danhhz** [comment]
Not just the `kv.rangefeed.enabled` cluster setting, but also the `changefeed.push.enabled` and the `kv.closed_timestamp.target_duration` and how all 3 relate. `kv.rangefeed.enabled` defaults to off, because there is some performance impact, but it's required for `changefeed.push.enabled` to be on, which is now the default. Action item for me is to take some measurement of what that performance impact is, so we can include it here.

**Comment by lhirata** [comment]
From Slack / Zendesk: I would suggest you guys add a quick sentence/note about cursors skipping the scan/table dump in the example at https://www.cockroachlabs.com/docs/stable/create-changefeed.html#start-a-new-changefeed-where-another-ended because I believe that https://www.cockroachlabs.com/docs/stable/create-changefeed.html#options is the only place I saw that which is easy to skip. this API/behavior makes sense though.

**Comment by rolandcrosby** [comment]
- [ ] Document why we always emit a full table scan following a schema change
- [ ] Document how our Avro schemas interact with Avro and Confluent schema evolution/compatibility rules

**Comment by rolandcrosby** [comment]
- [ ] Include pseudocode algorithm for how to consistently ingest data from a changefeed with resolved timestamps (i.e. which messages to ignore based on their updated timestamp, which to upsert, how to know you've seen everything up to a given timestamp, etc.)

**Comment by danhhz** [comment]
- [ ] As of #35529 we not longer need to use results_buffer_size for sinkless changefeeds. The server detects the `EXPERIMENTAL CHANGEFEED FOR` statement and does the right thing automatically. References to it should be removed from the docs.

**Comment by danhhz** [comment]
- [ ] Once https://github.com/cockroachdb/cockroach/pull/35661 merges we should mention that "kafka: client has run
out of available brokers to talk to (Is your cluster reachable?)" errors can be debugged by looking for lines in the logs with "[kafka-producer]" in them

**Comment by rolandcrosby** [comment]
- [ ] document URL parameters for Kafka sink TLS encryption (cockroachdb/cockroach#35510) and SASL/PLAIN authentication (cockroachdb/cockroach#35800)
