### ISSUE TITLE
Retrieve partitions using SQL 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4789]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec8p5vBpvOihNxkK?blocks=hide
PM: @awoods187 
Eng:

**Comment by ericharmeling** [comment]
https://github.com/cockroachdb/cockroach/issues/38436
https://github.com/cockroachdb/cockroach/issues/34907
https://docs.google.com/document/d/1XL4MT1fL257aloYsuwyt7ynkOIWct1qNMp_wNh2OvmU/edit?pli=1#heading=h.kcnc0iwv6q0m
https://cockroachlabs.slack.com/archives/CB8GCEW1G/p1550582818033300

**Comment by ericharmeling** [comment]
As far as I can tell, just the following doc page needs to be created, following the standard SQL statement page template:
- [ ] `SHOW PARTITIONS` page (under [SQL Statements](https://www.cockroachlabs.com/docs/stable/sql-statements.html) in the TOC)

We need to update some existing pages as well:
- [ ] A table row entry for `SHOW PARTITIONS` under [Data definition statements](https://www.cockroachlabs.com/docs/stable/sql-statements.html#data-definition-statements)
- [ ] Rewrite statements to show partitions in [Define Table Partitions](https://www.cockroachlabs.com/docs/dev/partitioning.html)
- [ ] Rewrite statements to show partitions in [Configure Replication Zones](https://www.cockroachlabs.com/docs/dev/configure-replication-zones.html)
- [ ] Rewrite statements to show partitions in the [Geo-Partitioning demo](https://www.cockroachlabs.com/docs/dev/demo-geo-partitioning.html#step-13-re-check-replica-distribution)

**Comment by ericharmeling** [comment]
Feature branch:
https://github.com/cockroachdb/docs/tree/show-partitions

**Comment by ericharmeling** [comment]
PR: #5242
