### ISSUE TITLE
Specify the order of aggregations 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4801]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recUUj8sRVt94jQeh?blocks=hide
PM: @awoods187 

- [x] Update built-in aggregation description strings and regenerate function docs
- [x] Add note to examples that use non-commutative aggregate functions (where necessary)

**Comment by ericharmeling** [comment]
https://github.com/cockroachdb/cockroach/pull/24815

**Comment by ericharmeling** [comment]
As far as I can tell, just the following doc page needs to be created, following the standard SQL statement page template:
- [ ] `SHOW PARTITIONS` page (under [SQL Statements](https://www.cockroachlabs.com/docs/stable/sql-statements.html) in the TOC)

We need to update some existing pages as well:
- [ ] A table row entry for `SHOW PARTITIONS` under [Data definition statements](https://www.cockroachlabs.com/docs/stable/sql-statements.html#data-definition-statements)
- [ ] Rewrite statements to show partitions in [Define Table Partitions](https://www.cockroachlabs.com/docs/dev/partitioning.html)
- [ ] Rewrite statements to show partitions in [Configure Replication Zones](https://www.cockroachlabs.com/docs/dev/configure-replication-zones.html)
- [ ] Rewrite statements to show partitions in the [Geo-Partitioning demo](https://www.cockroachlabs.com/docs/dev/demo-geo-partitioning.html#step-13-re-check-replica-distribution)

**Comment by ericharmeling** [comment]
There appear to be multiple issues/PR's about this, but I think this is the correct one: https://github.com/cockroachdb/cockroach/pull/38014 ...

@ridwanmsharif ... maybe we should talk for like 5-10 minutes about doc support for your work here?

**Comment by ericharmeling** [comment]
This brings up an issue with the function generator... see workaround: https://github.com/cockroachdb/cockroach/commit/6861b9f7b5e7381f6c2a0893b35e7f633cf25ad1
