### ISSUE TITLE
Licensing updates

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#4859]
Tasks:

- [x] Create a new Licensing page in the FAQs section
- [ ] Update references to "open source" and "core" throughout docs
- [x] After the release notes PR is merged, open a follow-up PR to add licensing-faqs.md to 19.2
