### ISSUE TITLE
Improve Search: Milestone B

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#4972]
Rolls up into #4704.

- [x] Search RFC reviewed by stakeholders (i.e., Jesse, Nate, Docs team)
- [x] Address feedback from reviewers
- [x] Complete wireframes for Search UX/UI
- [x] Informational interview with Netlify
       - Reached out to Jessica at Netlify to schedule.
