### ISSUE TITLE
Improve Search: Milestone C

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#5073]
- [x] Create wireframes (Carried over from Milestone B)
- [x] Write up results from wireframing session
- [x] Meet with internal collaborators (Marketing, Joe, Design, Dev Infrastructure)
- [x] Meet with Algolia about upgrading plan + figuring out next steps
- [x] Create list of tasks for consultant
