### ISSUE TITLE
Updates to cockroach demo for nodes and locality

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#5212]
- [x] `--nodes` flag (https://github.com/cockroachdb/cockroach/pull/39088)

- [x] `--locality` flag (https://github.com/cockroachdb/cockroach/issues/39450)

- [x] Create movr-statements-nodes.md file

**Comment by ericharmeling** [comment]
See #5221
